apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 9.2.4
  targetNamespace: argocd
  createNamespace: true
  bootstrap: true
  valuesContent: |-
    crds:
      install: true
    global:
      domain: argocd.localtest.me
    configs:
      params:
        server.insecure: true
