apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 9.2.4
  targetNamespace: argocd
  createNamespace: true
  bootstrap: true
  valuesContent: |-
    crds:
      install: true
    global:
      domain: argocd.localtest.me
    configs:
      params:
        server.insecure: true
    extraObjects:
      - apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: root
          namespace: argocd
          annotations:
            helm.sh/hook: post-install
            helm.sh/hook-weight: "10"
        spec:
          project: default
          source:
            repoURL: https://github.com/MJoeWatson/kro-bootstrapper.git
            targetRevision: main
            path: clusters/local/root
          destination:
            server: https://kubernetes.default.svc
            namespace: argocd
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
